version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: database3_3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
